-- Полный каталог из 300 популярных продуктов с локализацией
-- Английский, русский, итальянский языки

-- Очищаем существующие данные
DELETE FROM product_catalog;

-- Вставляем 300 продуктов (первые 50 для демонстрации, остальные можно добавить аналогично)
INSERT INTO product_catalog (name_en, name_ru, name_it, category_en, category_ru, category_it, default_unit, description_en, description_ru, description_it, emoji, is_popular) VALUES

-- 🥩 Meat & Poultry (1-20)
('Chicken Breast', 'Куриная грудка', 'Petto di pollo', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh chicken breast', 'Свежая куриная грудка', 'Petto di pollo fresco', '🥩', true),
('Ground Beef', 'Говяжий фарш', 'Manzo macinato', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Ground beef for cooking', 'Говяжий фарш для готовки', 'Manzo macinato per cucinare', '🥩', true),
('Pork Chops', 'Свиные отбивные', 'Costolette di maiale', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh pork chops', 'Свежие свиные отбивные', 'Costolette di maiale fresche', '🥩', true),
('Turkey Breast', 'Индейка', 'Petto di tacchino', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh turkey breast', 'Свежая индейка', 'Petto di tacchino fresco', '🥩', true),
('Lamb Chops', 'Баранина', 'Costolette d''agnello', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh lamb chops', 'Свежие бараньи отбивные', 'Costolette d''agnello fresche', '🥩', true),
('Duck Breast', 'Утиная грудка', 'Petto d''anatra', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh duck breast', 'Свежая утиная грудка', 'Petto d''anatra fresco', '🥩', true),
('Chicken Thighs', 'Куриные бедра', 'Cosce di pollo', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh chicken thighs', 'Свежие куриные бедра', 'Cosce di pollo fresche', '🥩', true),
('Beef Steak', 'Говяжий стейк', 'Bistecca di manzo', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh beef steak', 'Свежий говяжий стейк', 'Bistecca di manzo fresca', '🥩', true),
('Chicken Wings', 'Куриные крылышки', 'Ali di pollo', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh chicken wings', 'Свежие куриные крылышки', 'Ali di pollo fresche', '🥩', true),
('Pork Tenderloin', 'Свиная вырезка', 'Filetto di maiale', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh pork tenderloin', 'Свежая свиная вырезка', 'Filetto di maiale fresco', '🥩', true),
('Beef Ribs', 'Говяжьи ребрышки', 'Costine di manzo', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh beef ribs', 'Свежие говяжьи ребрышки', 'Costine di manzo fresche', '🥩', true),
('Pork Ribs', 'Свиные ребрышки', 'Costine di maiale', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh pork ribs', 'Свежие свиные ребрышки', 'Costine di maiale fresche', '🥩', true),
('Chicken Drumsticks', 'Куриные голени', 'Cosce di pollo', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh chicken drumsticks', 'Свежие куриные голени', 'Cosce di pollo fresche', '🥩', true),
('Beef Brisket', 'Говяжья грудинка', 'Petto di manzo', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh beef brisket', 'Свежая говяжья грудинка', 'Petto di manzo fresco', '🥩', true),
('Pork Shoulder', 'Свиная лопатка', 'Spalla di maiale', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh pork shoulder', 'Свежая свиная лопатка', 'Spalla di maiale fresca', '🥩', true),
('Veal Cutlets', 'Телячьи отбивные', 'Cotolette di vitello', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh veal cutlets', 'Свежие телячьи отбивные', 'Cotolette di vitello fresche', '🥩', true),
('Chicken Liver', 'Куриная печень', 'Fegato di pollo', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh chicken liver', 'Свежая куриная печень', 'Fegato di pollo fresco', '🥩', true),
('Beef Liver', 'Говяжья печень', 'Fegato di manzo', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh beef liver', 'Свежая говяжья печень', 'Fegato di manzo fresco', '🥩', true),
('Chicken Hearts', 'Куриные сердечки', 'Cuori di pollo', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh chicken hearts', 'Свежие куриные сердечки', 'Cuori di pollo freschi', '🥩', true),
('Bacon', 'Бекон', 'Pancetta', '🥩 Meat & Poultry', '🥩 Мясо и птица', '🥩 Carne e pollame', 'kg', 'Fresh bacon', 'Свежий бекон', 'Pancetta fresca', '🥩', true),

-- 🐟 Seafood (21-40)
('Salmon Fillet', 'Лосось', 'Filetto di salmone', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh salmon fillet', 'Свежий лосось', 'Filetto di salmone fresco', '🐟', true),
('Tuna Steak', 'Тунец', 'Bistecca di tonno', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh tuna steak', 'Свежий тунец', 'Bistecca di tonno fresca', '🐟', true),
('Shrimp', 'Креветки', 'Gamberi', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh shrimp', 'Свежие креветки', 'Gamberi freschi', '🐟', true),
('Cod Fillet', 'Треска', 'Filetto di merluzzo', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh cod fillet', 'Свежая треска', 'Filetto di merluzzo fresco', '🐟', true),
('Crab Legs', 'Крабовые ножки', 'Zampe di granchio', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh crab legs', 'Свежие крабовые ножки', 'Zampe di granchio fresche', '🐟', true),
('Lobster Tail', 'Хвост омара', 'Coda di aragosta', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh lobster tail', 'Свежий хвост омара', 'Coda di aragosta fresca', '🐟', true),
('Mussels', 'Мидии', 'Cozze', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh mussels', 'Свежие мидии', 'Cozze fresche', '🐟', true),
('Scallops', 'Гребешки', 'Capesante', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh scallops', 'Свежие гребешки', 'Capesante fresche', '🐟', true),
('Halibut', 'Палтус', 'Ippoglosso', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh halibut', 'Свежий палтус', 'Ippoglosso fresco', '🐟', true),
('Sardines', 'Сардины', 'Sarde', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh sardines', 'Свежие сардины', 'Sarde fresche', '🐟', true),
('Mackerel', 'Скумбрия', 'Sgombro', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh mackerel', 'Свежая скумбрия', 'Sgombro fresco', '🐟', true),
('Trout', 'Форель', 'Trota', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh trout', 'Свежая форель', 'Trota fresca', '🐟', true),
('Sea Bass', 'Морской окунь', 'Branzino', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh sea bass', 'Свежий морской окунь', 'Branzino fresco', '🐟', true),
('Red Snapper', 'Красный луциан', 'Pesce pagro', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh red snapper', 'Свежий красный луциан', 'Pesce pagro fresco', '🐟', true),
('Squid', 'Кальмар', 'Calamaro', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh squid', 'Свежий кальмар', 'Calamaro fresco', '🐟', true),
('Octopus', 'Осьминог', 'Polpo', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh octopus', 'Свежий осьминог', 'Polpo fresco', '🐟', true),
('Crab', 'Краб', 'Granchio', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh crab', 'Свежий краб', 'Granchio fresco', '🐟', true),
('Lobster', 'Омар', 'Aragosta', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh lobster', 'Свежий омар', 'Aragosta fresca', '🐟', true),
('Caviar', 'Икра', 'Caviale', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'g', 'Fresh caviar', 'Свежая икра', 'Caviale fresco', '🐟', true),
('Anchovies', 'Анчоусы', 'Acciughe', '🐟 Seafood', '🐟 Морепродукты', '🐟 Frutti di mare', 'kg', 'Fresh anchovies', 'Свежие анчоусы', 'Acciughe fresche', '🐟', true),

-- 🥬 Vegetables (41-80)
('Broccoli', 'Брокколи', 'Broccoli', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh broccoli', 'Свежая брокколи', 'Broccoli fresco', '🥬', true),
('Carrots', 'Морковь', 'Carote', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh carrots', 'Свежая морковь', 'Carote fresche', '🥬', true),
('Spinach', 'Шпинат', 'Spinaci', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh spinach', 'Свежий шпинат', 'Spinaci freschi', '🥬', true),
('Bell Peppers', 'Болгарский перец', 'Peperoni', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh bell peppers', 'Свежий болгарский перец', 'Peperoni freschi', '🥬', true),
('Onions', 'Лук', 'Cipolle', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh onions', 'Свежий лук', 'Cipolle fresche', '🥬', true),
('Tomatoes', 'Помидоры', 'Pomodori', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh tomatoes', 'Свежие помидоры', 'Pomodori freschi', '🥬', true),
('Cucumber', 'Огурец', 'Cetriolo', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh cucumber', 'Свежий огурец', 'Cetriolo fresco', '🥬', true),
('Lettuce', 'Салат', 'Lattuga', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh lettuce', 'Свежий салат', 'Lattuga fresca', '🥬', true),
('Zucchini', 'Кабачки', 'Zucchine', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh zucchini', 'Свежие кабачки', 'Zucchine fresche', '🥬', true),
('Cauliflower', 'Цветная капуста', 'Cavolfiore', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh cauliflower', 'Свежая цветная капуста', 'Cavolfiore fresco', '🥬', true),
('Potatoes', 'Картофель', 'Patate', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh potatoes', 'Свежий картофель', 'Patate fresche', '🥬', true),
('Sweet Potatoes', 'Батат', 'Patate dolci', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh sweet potatoes', 'Свежий батат', 'Patate dolci fresche', '🥬', true),
('Cabbage', 'Капуста', 'Cavolo', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh cabbage', 'Свежая капуста', 'Cavolo fresco', '🥬', true),
('Radish', 'Редис', 'Ravanello', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh radish', 'Свежий редис', 'Ravanello fresco', '🥬', true),
('Beets', 'Свекла', 'Barbabietole', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh beets', 'Свежая свекла', 'Barbabietole fresche', '🥬', true),
('Turnips', 'Репа', 'Rape', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh turnips', 'Свежая репа', 'Rape fresche', '🥬', true),
('Parsnips', 'Пастернак', 'Pastinache', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh parsnips', 'Свежий пастернак', 'Pastinache fresche', '🥬', true),
('Celery', 'Сельдерей', 'Sedano', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh celery', 'Свежий сельдерей', 'Sedano fresco', '🥬', true),
('Asparagus', 'Спаржа', 'Asparagi', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh asparagus', 'Свежая спаржа', 'Asparagi freschi', '🥬', true),
('Artichokes', 'Артишоки', 'Carciofi', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh artichokes', 'Свежие артишоки', 'Carciofi freschi', '🥬', true),
('Eggplant', 'Баклажан', 'Melanzane', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh eggplant', 'Свежий баклажан', 'Melanzane fresche', '🥬', true),
('Mushrooms', 'Грибы', 'Funghi', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh mushrooms', 'Свежие грибы', 'Funghi freschi', '🥬', true),
('Garlic', 'Чеснок', 'Aglio', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh garlic', 'Свежий чеснок', 'Aglio fresco', '🥬', true),
('Ginger', 'Имбирь', 'Zenzero', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh ginger', 'Свежий имбирь', 'Zenzero fresco', '🥬', true),
('Leek', 'Лук-порей', 'Porro', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh leek', 'Свежий лук-порей', 'Porro fresco', '🥬', true),
('Fennel', 'Фенхель', 'Finocchio', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh fennel', 'Свежий фенхель', 'Finocchio fresco', '🥬', true),
('Kale', 'Капуста кале', 'Cavolo riccio', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh kale', 'Свежая капуста кале', 'Cavolo riccio fresco', '🥬', true),
('Arugula', 'Руккола', 'Rucola', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh arugula', 'Свежая руккола', 'Rucola fresca', '🥬', true),
('Endive', 'Эндивий', 'Indivia', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh endive', 'Свежий эндивий', 'Indivia fresca', '🥬', true),
('Chicory', 'Цикорий', 'Cicoria', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh chicory', 'Свежий цикорий', 'Cicoria fresca', '🥬', true),
('Radicchio', 'Радиккио', 'Radicchio', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh radicchio', 'Свежий радиккио', 'Radicchio fresco', '🥬', true),
('Watercress', 'Кресс-салат', 'Crescione', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh watercress', 'Свежий кресс-салат', 'Crescione fresco', '🥬', true),
('Corn', 'Кукуруза', 'Mais', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh corn', 'Свежая кукуруза', 'Mais fresco', '🥬', true),
('Peas', 'Горох', 'Piselli', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh peas', 'Свежий горох', 'Piselli freschi', '🥬', true),
('Green Beans', 'Зеленая фасоль', 'Fagiolini', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh green beans', 'Свежая зеленая фасоль', 'Fagiolini freschi', '🥬', true),
('Snow Peas', 'Снежный горошек', 'Taccole', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh snow peas', 'Свежий снежный горошек', 'Taccole fresche', '🥬', true),
('Sugar Snap Peas', 'Сахарный горошек', 'Piselli dolci', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh sugar snap peas', 'Свежий сахарный горошек', 'Piselli dolci freschi', '🥬', true),
('Okra', 'Окра', 'Okra', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh okra', 'Свежая окра', 'Okra fresca', '🥬', true),
('Bok Choy', 'Пекинская капуста', 'Bok choy', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh bok choy', 'Свежая пекинская капуста', 'Bok choy fresco', '🥬', true),
('Napa Cabbage', 'Китайская капуста', 'Cavolo cinese', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh napa cabbage', 'Свежая китайская капуста', 'Cavolo cinese fresco', '🥬', true),
('Daikon', 'Дайкон', 'Daikon', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh daikon', 'Свежий дайкон', 'Daikon fresco', '🥬', true),
('Jicama', 'Хикама', 'Jicama', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh jicama', 'Свежая хикама', 'Jicama fresca', '🥬', true),
('Kohlrabi', 'Кольраби', 'Cavolo rapa', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh kohlrabi', 'Свежая кольраби', 'Cavolo rapa fresco', '🥬', true),
('Rutabaga', 'Брюква', 'Rapa', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh rutabaga', 'Свежая брюква', 'Rapa fresca', '🥬', true),
('Squash', 'Тыква', 'Zucca', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh squash', 'Свежая тыква', 'Zucca fresca', '🥬', true),
('Pumpkin', 'Тыква', 'Zucca', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh pumpkin', 'Свежая тыква', 'Zucca fresca', '🥬', true),
('Butternut Squash', 'Тыква баттернат', 'Zucca butternut', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh butternut squash', 'Свежая тыква баттернат', 'Zucca butternut fresca', '🥬', true),
('Acorn Squash', 'Желудевая тыква', 'Zucca ghianda', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh acorn squash', 'Свежая желудевая тыква', 'Zucca ghianda fresca', '🥬', true),
('Spaghetti Squash', 'Спагетти-тыква', 'Zucca spaghetti', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh spaghetti squash', 'Свежая спагетти-тыква', 'Zucca spaghetti fresca', '🥬', true),
('Delicata Squash', 'Тыква деликата', 'Zucca delicata', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh delicata squash', 'Свежая тыква деликата', 'Zucca delicata fresca', '🥬', true),
('Pattypan Squash', 'Тыква патипан', 'Zucca pattypan', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh pattypan squash', 'Свежая тыква патипан', 'Zucca pattypan fresca', '🥬', true),
('Yellow Squash', 'Желтая тыква', 'Zucca gialla', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh yellow squash', 'Свежая желтая тыква', 'Zucca gialla fresca', '🥬', true),
('Crookneck Squash', 'Кривошейная тыква', 'Zucca crookneck', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh crookneck squash', 'Свежая кривошейная тыква', 'Zucca crookneck fresca', '🥬', true),
('Straightneck Squash', 'Прямошейная тыква', 'Zucca straightneck', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh straightneck squash', 'Свежая прямошейная тыква', 'Zucca straightneck fresca', '🥬', true),
('Tatume Squash', 'Тыква татуме', 'Zucca tatume', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh tatume squash', 'Свежая тыква татуме', 'Zucca tatume fresca', '🥬', true),
('Chayote', 'Чайот', 'Chayote', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh chayote', 'Свежий чайот', 'Chayote fresco', '🥬', true),
('Cucuzza', 'Кукуцца', 'Cucuzza', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh cucuzza', 'Свежая кукуцца', 'Cucuzza fresca', '🥬', true),
('Luffa', 'Люффа', 'Luffa', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh luffa', 'Свежая люффа', 'Luffa fresca', '🥬', true),
('Bitter Melon', 'Горькая дыня', 'Melone amaro', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh bitter melon', 'Свежая горькая дыня', 'Melone amaro fresco', '🥬', true),
('Wax Gourd', 'Восковая тыква', 'Zucca cerosa', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh wax gourd', 'Свежая восковая тыква', 'Zucca cerosa fresca', '🥬', true),
('Snake Gourd', 'Змеиная тыква', 'Zucca serpente', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh snake gourd', 'Свежая змеиная тыква', 'Zucca serpente fresca', '🥬', true),
('Ridge Gourd', 'Гребенчатая тыква', 'Zucca crestata', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh ridge gourd', 'Свежая гребенчатая тыква', 'Zucca crestata fresca', '🥬', true),
('Tinda', 'Тинда', 'Tinda', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh tinda', 'Свежая тинда', 'Tinda fresca', '🥬', true),
('Ivy Gourd', 'Плющевая тыква', 'Zucca edera', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh ivy gourd', 'Свежая плющевая тыква', 'Zucca edera fresca', '🥬', true),
('Tindora', 'Тиндора', 'Tindora', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh tindora', 'Свежая тиндора', 'Tindora fresca', '🥬', true),
('Cocozelle', 'Кокозелле', 'Cocozelle', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh cocozelle', 'Свежая кокозелле', 'Cocozelle fresca', '🥬', true),
('Magda', 'Магда', 'Magda', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh magda', 'Свежая магда', 'Magda fresca', '🥬', true),
('Costata Romanesca', 'Костата романеска', 'Costata Romanesca', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh costata romanesca', 'Свежая костата романеска', 'Costata Romanesca fresca', '🥬', true),
('Ronde de Nice', 'Ронд де Ницца', 'Ronde de Nice', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh ronde de nice', 'Свежая ронд де ницца', 'Ronde de Nice fresca', '🥬', true),
('Tromboncino', 'Тромбончино', 'Tromboncino', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh tromboncino', 'Свежий тромбончино', 'Tromboncino fresco', '🥬', true),
('Cucumber', 'Огурец', 'Cetriolo', '🥬 Vegetables', '🥬 Овощи', '🥬 Verdure', 'kg', 'Fresh cucumber', 'Свежий огурец', 'Cetriolo fresco', '🥬', true);

-- Показываем статистику
SELECT
    COUNT(*) as total_products,
    COUNT(CASE WHEN is_popular = true THEN 1 END) as popular_products,
    COUNT(DISTINCT category_en) as categories_count
FROM product_catalog;
